---
- name: Import locale tasks.
  ansible.builtin.import_tasks:
    file: sub_locale.yml
  when: linux_general_run_locale

- name: Import locale tasks.
  ansible.builtin.import_tasks:
    file: sub_hostname.yml
  when: linux_general_run_hostname
 
- name: Import selinux tasks.
  ansible.builtin.import_tasks:
    file: sub_selinux.yml
  when: linux_general_run_selinux

- name: Import sysctl tasks.
  ansible.builtin.import_tasks:
    file: sub_sysctl.yml
  when: linux_general_run_sysctl

- name: Import services tasks.
  ansible.builtin.import_tasks:
    file: sub_services.yml
  when: linux_general_run_services

- name: Import resolve tasks.
  ansible.builtin.import_tasks:
    file: sub_resolve.yml
  when: linux_general_run_resolve

- name: Import default_target tasks.
  ansible.builtin.import_tasks:
    file: sub_default_target.yml
  when: linux_general_run_default_target

- name: Import files tasks.
  ansible.builtin.import_tasks:
    file: sub_files.yml
  when: linux_general_run_files

- name: Import mount tasks.
  ansible.builtin.import_tasks:
    file: sub_mount.yml
  when: linux_general_run_mount

- name: Import users tasks.
  ansible.builtin.import_tasks:
    file: sub_users.yml
  when: linux_general_run_users

- name: Import timezone tasks.
  ansible.builtin.import_tasks:
    file: sub_timezone.yml
  when: linux_general_run_timezone

- name: Import dnf tasks.
  ansible.builtin.import_tasks:
    file: sub_dnf.yml
  when: linux_general_run_dnf

- name: Import sudoers tasks.
  ansible.builtin.import_tasks:
    file: sub_sudoers.yml
  when: linux_general_run_sudoers

- name: Import cron tasks.
  ansible.builtin.import_tasks:
    file: sub_cron.yml
  when: linux_general_run_cron

- name: Import logrotate tasks.
  ansible.builtin.import_tasks:
    file: sub_logrotate_base.yml
  when: linux_general_run_logrotate_base

- name: Import rsyslog tasks.
  ansible.builtin.import_tasks:
    file: sub_rsyslog.yml
  when: linux_general_run_rsyslog

- name: Import firewalld tasks.
  ansible.builtin.import_tasks:
    file: sub_firewalld.yml
  when: linux_general_run_firewalld

- name: Import chrony tasks.
  ansible.builtin.import_tasks:
    file: sub_chrony.yml
  when: linux_general_run_chrony
