---
- name: Check if rsyslog runs
  ansible.builtin.systemd:
    name: rsyslog
  register: rsyslog_status
  check_mode: false

- name: Configure rsyslog conf.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  register: rsyslog_conf
  loop:
    - src: sub_rsyslog/rsyslog.conf.j2
      dest: /etc/rsyslog.conf
  when:
    - rsyslog_status.status.UnitFileState == "enabled" 
    - rsyslog_status.status.ActiveState == "active" 

- name: Configure rsyslog conf.d.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  register: rsyslog_conf_d
  loop:
    - src: sub_rsyslog/users.conf.j2
      dest: /etc/rsyslog.d/users.conf
  when: 
    - linux_general_rsyslog_facilities|length > 0
    - rsyslog_status.status.UnitFileState == "enabled" 
    - rsyslog_status.status.ActiveState == "active" 

- name: Restart rsyslog service 
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  when: >
   (rsyslog_conf is defined and rsyslog_conf.changed) or
   (rsyslog_conf_d is defined and rsyslog_conf_d.changed)