---
- name: Configure sudoers.
  ansible.builtin.template:
    src: sub_sudoers/sudoers_user.j2
    dest: /etc/sudoers.d/sudoers_user
    owner: root
    group: root
    mode: '0644'
  loop:
  when: linux_general_sudoers|length > 0

